#pragma once
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <netinet/in.h>
#include <unistd.h>
#include <fcntl.h>
#include "perso.h"
#include "net.h"
#include "map_op.h"
#include "req.h"
#include "utile.h"
#include "time.h"
#include "demographie.h"
#include "acount.h"
